# Generated by Django 3.1 on 2020-10-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_remove_pickup_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='seller',
        ),
    ]
