# Generated by Django 3.1 on 2020-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usermanagement', '0002_auto_20201001_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='details',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
